database:
  url: "postgresql://postgres:password123@localhost:5432/readcommend?sslmode=disable"
  max_connections: 10
  max_connection_idle_time: 5m

log:
  level: debug

server:
  cors_allowed_origins: [ "http://localhost:8080" ]
  request_read_header_timeout: 5s
  bind: :5001
